config/routes.rb
Ofx::Application.routes.draw do

  resources :links
  
  post 'admin/home_heroes', to: 'home_heroes#create_and_update'

  resources :standard_changes
  get 'standard_changes/:id/archive', to: 'standard_changes#archive'
  
  resources :comments, :except => [:index]
  
  resources :versions, except: [:index]
  
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations', passwords: 'passwords' }
  
  resources :users, except: [:new, :create]
  post 'users/new_by_admin',          to: 'users#new_by_admin'
  
  scope :ajax do
    get 'users/toggle',               to: 'users#toggle'
    get 'api_docs/start_stream',      to: 'api_docs#start_stream'
    get 'api_docs/update',            to: 'api_docs#update'
    get 'api_docs/insert_nav',        to: 'api_docs#insert_nav'
    get 'api_docs/test',              to: 'api_docs#test'
  end
  
  

  root to: 'welcome#index'
  

  resources :companies
  resources :contents
  get 'contents/page/:ident', to: "contents#page_display"
  
  resources :minutes
  get '/minutes/ajax/toggle_published', to: 'minutes#toggle_published'
  
  resources :news_items
  
  get   '/contact_form',        to: "contact_form#display"
  post  '/contact_form',        to: "contact_form#send_form_mail"
  
  get 'admin/dashboard', to: 'admin#dashboard'
end

app/views/admin/_all_users.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title All Users
  .panel-body
    = link_to 'Show all users', users_path
    (new page)

app/views/admin/_heroes.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Hero Image (max 10)
  .panel-body
    = form_tag(admin_home_heroes_path, :id => 'home_heroes', :multipart => true, :role => "form") do
      - if !@home_heroes.blank?
        %table.table-condensed
          %thead
            %th Active
            %th
            %th Delete
          %tbody
            - @home_heroes.each do |home_hero|
              %tr
                %td
                  = radio_button_tag("home_hero[id]", home_hero.id, home_hero.active?)
                %td
                  .form-group
                    = image_tag(home_hero.hero_image(:list_display))
                %td{align: 'center'}
                  .form-group
                    = check_box_tag("home_hero[delete][]", home_hero.id)
      - if @home_heroes.length <= 10
        %p 
          Upload a new hero image (will be set as active):
          = file_field_tag "home_hero[hero_image]"

      %p
        .form-group= submit_tag 'Save/Update/Delete', :class => 'btn btn-primary'

app/views/admin/_links.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Useful Links
  .panel-body
    %table.table-condensed
      %tbody
        - unless @links.blank?
          - @links.each do |link|
            %tr
              %td
                = form_tag "/links/#{link.id}", :method => 'put', :role => 'form', :class => 'form-inline' do 
                  .form-group
                    = text_field_tag 'link[url]', link.url, :class => "form-control input-sm", :placeholder => "Link url"
                  .form-group
                    = text_field_tag 'link[title]', link.title, :class => "form-control input-sm", :placeholder => "Link text"
                  %button{ :type => 'submit', :class => 'btn btn-sm btn-primary' } Save
                  .form-group
                    = link_to 'Delete', link, :method => :delete, :type => 'button', :class => 'btn btn-sm btn-danger', :data => { :confirm => 'Are you sure?' }
        %tr
          %td
            = form_tag links_path, :method => 'post', :role => 'form', :class => 'form-inline' do
              .form-group
                = text_field_tag 'link[url]', nil, :class => "form-control input-sm", :placeholder => "Link url"
              .form-group
                = text_field_tag 'link[title]', nil, :class => "form-control input-sm", :placeholder => "Link text"
                %button{ :type => 'submit', :class => 'btn btn-sm btn-primary' } Create
 

app/views/admin/_member_companies.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Member Companies
  .panel-body
    - if companies.blank?
      %p No member companies yet
    - else
      %table.table-condensed
        %thead
          %tr
            %th
            %th Name
            %th URL
            %th Contact
            %th Join Date

        %tbody
          - companies.each do |company|
            %tr
              %td= company.logo.blank? ? '(no logo)' : image_tag(company.logo.url(:listing))
              %td= company.name
              %td= link_to company.url, company.url
              %td= company.contact.blank? ? '(none)' : company.contact.name
              %td= company.joined.blank? ? '' : company.joined.strftime('%d-%b-%Y')
              %td{ :style => 'text-align: center;'}
              %td= render :partial => 'components/show_edit_delete', :locals => { :model => 'company', :instance => company }
        
    %br
      = link_to 'New member company', new_company_path, :type => 'button', :class => 'btn btn-primary'
          

app/views/admin/_members_to_accept.html.haml
%div{ :class => members_waiting.blank? ? "panel panel-default" : "panel panel-warning" }
  .panel-heading
    %h3.panel-title 
      Members Awaiting Approval
  .panel-body
    %table.table-condensed#users
      %thead
        %tr
          %th Approve
          %th Name
          %th Email
          %th Company
      %tbody
        - members_waiting.each do |user|
          %tr
            %td.text-center
              = render :partial => 'components/user_status', :locals => { :user => user }
            %td= user.name
            %td= user.email
            %td= user.company_or_org

app/views/admin/_minutes.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Meeting Minutes
  .panel-body
    - if minutes.blank?
      %p No minutes yet
    - else
      %table.table-condensed
        %thead
          %tr
            %th Date
            %th Meeting
            %th Location
            %th{ :colspan => 3 } Actions
        %tbody
          - minutes.each do |minute|
            %tr
              %td= minute.date
              %td= textify(minute.meeting)
              %td= minute.location
              %td= render :partial => 'components/show_edit_delete', :locals => { :model => 'minute', :instance => minute }
        
    %br
      = link_to 'New minutes', new_minute_path, :type => 'button', :class => 'btn btn-primary'
          

app/views/admin/_miscellaneous_content.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Miscellaneous Content
  .panel-body
    - if contents.blank?
      %p No miscellaneous content yet
    - else
      %table.table-condensed
        %thead
          %tr
            %th Identifier
            %th Title
            %th Image
            %th PDF
        %tbody
          - contents.each do |content|
            %tr
              %td= content.identifier
              %td= content.title
              %td= content.image.blank? ? '(none)' : image_tag(content.image(:list)) 
              %td= content.pdf.blank? ? '(none)' : (link_to image_tag('pdf_icon.png'), content.pdf.url)
              %td= render :partial => 'components/show_edit_delete', :locals => { :model => 'content', :instance => content }
        
    %br
      = link_to 'New miscellaneous content', new_content_path, :type => 'button', :class => 'btn btn-primary'
          

app/views/admin/_news.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title News Items
  .panel-body
    - if @news_items.blank?
      %p No news items yet
    - else
      %table.table-condensed
        %thead
          %tr
            %th Date
            %th Headline
        %tbody
          - @news_items.each do |item|
            %tr
              %td= item.date
              %td= item.headline
              %td= render :partial => 'components/show_edit_delete', :locals => { :model => 'news_item', :instance => item }
        
    %br
      = link_to 'New news item', new_news_item_path, :type => 'button', :class => 'btn btn-primary'
          

app/views/admin/_user_docs.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Update API documentation
  .panel-body
    %p.text-danger NOTE: At the moment these are synchronous processes, so they tie up the server while running.
    %table.table-condensed.manage-api
      %tr
        %td
          %p
            %b FIRST:
            Pull the latest version of the OpenFX repository on github and make the documentation.
          = form_tag '/ajax/api_docs/update', id: 'pull-from-github', method: 'get' do
            .form-group
              = text_field_tag :release, nil,class: 'form-control', :placeholder => 'Release'
            .form-group
              %button{ :type => 'submit', :class => 'btn btn-sm btn-default btn-primary' } Pull and Make
          %br
          = content_tag('div', nil, class: 'update-status', data: { running: image_url('ajax-running.gif') })
      %tr
        %td(colspan='2')
          %p           
            %b SECOND:
            Parse the documentation HTML to insert navbars at the top of the documentation.
          = form_tag '/ajax/api_docs/insert_nav', id: 'insert-navbars', method: 'post' do
            .btn-group
              - Rails.configuration.ofx[:support_docs][:docs].each do |doc|
                %button{ :type => 'submit', :class => 'btn btn-sm btn-default btn-info', id: doc } 
                  = "#{doc.titlecase.gsub(/_/,' ')}"
          %br
          = content_tag('div', nil, class: 'insert-nav-status', data: { running: image_url('ajax-running.gif') })
       

app/views/admin/_versions.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title OFX Standard Versions
  .panel-body
    - if @versions.blank?
      %p There are no versions
    - else
      %table.table-condensed
        %thead
          %tr
            %th Current
            %th Version
            %th Status
            - if user_signed_in? and current_user.has_role? :admin
              %th{ :colspan => 3 }
        %tbody
          - @versions.each do |v|
            %tr{class: v.current? ? 'bg-success' : '' }
              %td
                - if v.current?
                  %span.glyphicon.glyphicon-hand-right
              %td
                %b= v.version
              %td= Rails.configuration.ofx[:version_status][v.status.to_sym]
              - if user_signed_in? and current_user.has_role? :admin
                %td= link_to 'Edit', edit_version_path(v)
                %td= link_to 'Delete', v, :method => :delete, :data => { :confirm => 'Are you sure?' }

    = link_to 'New Version', new_version_path, :type => 'button', :class => 'btn btn-primary'

app/views/admin/dashboard.html.haml
.container
  %h2 Administrative Dashboard
  = link_to('Current proposed standard change', standard_change(@proposed_standard), :type => 'button', :class => 'btn btn-default') unless @proposed_standard.nil?
  .admin.btn-group
    = link_to 'News Items', '#news', :type => 'button', :class => 'btn btn-default'
    = link_to 'Minutes', '#minutes', :type => 'button', :class => 'btn btn-default'
    = link_to 'Misc. Content', '#content', :type => 'button', :class => 'btn btn-default'
    = link_to 'Member Companies', '#companies', :type => 'button', :class => 'btn btn-default'
    = link_to 'All Users <span class="glyphicon glyphicon-circle-arrow-right"></span>'.html_safe, users_path, :type => 'button', :class => 'btn btn-default'
    = link_to 'Standard Changes <span class="glyphicon glyphicon-circle-arrow-right"></span>'.html_safe, standard_changes_path, :type => 'button', :class => 'btn btn-default'

  - if !@members_waiting.blank?
    .row    
      .col-md-12#content
        = render :partial => "members_to_accept", locals: { members_waiting: @members_waiting }
  .row
    .col-md-12#news
      = render :partial => "news", locals: { news_items: @news_items }
  .row
    .col-md-6#user_docs
      = render :partial => "user_docs"
    .col-md-6#versions
      = render :partial => "versions", locals: { versions: @versions }
  .row
    .col-md-12#minutes
      = render :partial => "minutes", locals: { minutes: @minutes }
  .row
    .col-md-12#content
      = render :partial => "miscellaneous_content", locals: { contents: @contents }
  .row
    .col-md-6#links
      = render :partial => "links", locals: {links: @links }
    .col-md-6#hero
      = render :partial => "heroes", locals: { home_heroes: @home_heroes }
  .row#companies
    = render :partial => "member_companies", locals: { companies: @companies }